name: Publish Latest Docker Image

on:
    push:
        branches:
            - 'main'

env:
    PHP_VERSION: '8.1'
    DOCKER_HUB_REPO: 'rushlowdev/php-cli'

jobs:
    push_to_registry:
        name: Push Latest PHP Images to Docker Hub
        runs-on: ubuntu-latest
        steps:
            -   name: Check out the repo
                uses: actions/checkout@v2

            -   name: Log in to Docker Hub
                uses: docker/login-action@v1
                with:
                    username: ${{ secrets.DOCKER_HUB_USER }}
                    password: ${{ secrets.DOCKER_HUB_TOKEN }}

            -   name: Extract metadata (tags, labels) for Docker
                id: meta
                uses: docker/metadata-action@v3
                with:
                    images: rushlowdev/php-cli

            -   name: Build and push CLI image
                uses: docker/build-push-action@v2
                with:
                    context: ./cli
                    push: true
                    tags: ${{ env.DOCKER_HUB_REPO }}:latest-cli
                    labels: ${{ steps.meta.outputs.labels }}

            -   name: Build and push FPM image
                uses: docker/build-push-action@v2
                with:
                    context: ./fpm
                    push: true
                    tags: ${{ env.DOCKER_HUB_REPO }}:latest-fpm
                    labels: ${{ steps.meta.outputs.labels }}
