name: Publish Released Docker Image

on:
    release:
        types:
            - published
        branches:
            - '8.1.x'

env:
    PHP_VERSION: '8.1'
    DOCKER_HUB_REPO: 'rushlowdev/php'

jobs:
    push_to_registry:
        name: Push Released PHP Images to Docker Hub
        runs-on: ubuntu-latest
        steps:
            -   name: Check out the repo
                uses: actions/checkout@v2

            -   name: Log in to Docker Hub
                uses: docker/login-action@v1
                with:
                    username: ${{ secrets.DOCKER_HUB_USER }}
                    password: ${{ secrets.DOCKER_HUB_TOKEN }}

            -   name: Extract metadata (tags, labels) for Docker
                id: meta
                uses: docker/metadata-action@v3
                with:
                    images: rushlowdev/php

            -   name: Build and push CLI image
                uses: docker/build-push-action@v2
                with:
                    context: ./cli
                    push: true
                    tags: ${{ env.DOCKER_HUB_REPO }}:${{ env.PHP_VERSION }}-cli
                    labels: ${{ steps.meta.outputs.labels }}

            -   name: Build and push FPM image
                uses: docker/build-push-action@v2
                with:
                    context: ./fpm
                    push: true
                    tags: ${{ env.DOCKER_HUB_REPO }}:${{ env.PHP_VERSION }}-fpm
                    labels: ${{ steps.meta.outputs.labels }}
