name: Publish Released Docker Image

on:
    release:
        types:
            - published
        branches:
            - '7.4.x'

env:
    PHP_VERSION: '7.4'

jobs:
    push_to_registry:
        name: Push Docker image to Docker Hub
        runs-on: ubuntu-latest
        steps:
            -   name: Check out the repo
                uses: actions/checkout@v2

            -   name: Log in to Docker Hub
                uses: docker/login-action@v1
                with:
                    username: ${{ secrets.DOCKER_HUB_USER }}
                    password: ${{ secrets.DOCKER_HUB_TOKEN }}

            -   name: Extract metadata (tags, labels) for Docker
                id: meta
                uses: docker/metadata-action@v3
                with:
                    images: rushlowdev/php-cli

            -   name: Build and push CLI image
                uses: docker/build-push-action@v2
                with:
                    context: ./cli
                    push: true
                    tags: ${{ steps.meta.outputs.tags }}-cli
                    labels: ${{ steps.meta.outputs.labels }}

            -   name: Build and push FPM image
                uses: docker/build-push-action@v2
                with:
                    context: ./fpm
                    push: true
                    tags: ${{ steps.meta.outputs.tags }}-fpm
                    labels: ${{ steps.meta.outputs.labels }}

#            - name: Build and push Docker CLI image
#              uses: docker/build-push-action@v2
#              with:
#                  context: ./cli
#                  push: true
#                  tags: ${{ steps.meta.outputs.tags }}-cli
#                  labels: ${{ steps.meta.outputs.labels }}
#
#            -   name: Build and push Docker FPM image
#                uses: docker/build-push-action@v2
#                with:
#                    context: ./fpm
#                    push: true
#                    tags: ${{ steps.meta.outputs.tags }}-fpm
#                    labels: ${{ steps.meta.outputs.labels }}
